---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellodocker-deployment
spec:
  selector:
    matchLabels:
      app: hellodocker-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: hellodocker-deployment
    spec:
      containers:
      - name: nginx-helloworld
        image: raviosanchez/hellodocker
        ports:
        - containerPort: 80
